
import { Category, TravelCard } from './types';

export const INITIAL_DATA: TravelCard[] = [
  // Day 0
  {
    id: '0-1',
    day: 0,
    time: '18:00',
    title: '城市商旅-桃園航空館',
    subTitle: '入住準備',
    description: '位於桃園機場附近，方便隔天一早的航班。',
    category: Category.LOGISTICS,
    locationKeyword: 'City Suites Gateway Hotel',
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=600',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  // Day 1
  {
    id: '1-1',
    day: 1,
    time: '11:05',
    title: '中華航空 CI 154',
    category: Category.HUB,
    flightInfo: {
      flightNumber: 'CI 154',
      confirmationCode: 'TPE-NGO',
      origin: 'TPE - 桃園',
      destination: 'NGO - 中部國際',
      class: 'Economy',
      duration: '2h 55m',
      passengerNames: ['PaoPao', '孟哲']
    },
    isDeleted: false,
    expenses: [],
    notes: ['填好 Visit Japan Web QR Code']
  },
  {
    id: '1-1-t',
    day: 1,
    time: '12:37',
    title: '名鐵機場特急 μ-SKY',
    subTitle: '中部國際機場 -> 名古屋站',
    description: '最快 28 分鐘直達。用西瓜卡搭配對號座車票。',
    category: Category.TRANSPORT,
    isDeleted: false,
    expenses: [{ id: 'e1', item: '乘車券', amount: 980 }, { id: 'e2', item: '特急券', amount: 450 }],
    notes: []
  },
  {
    id: '1-2',
    day: 1,
    time: '13:30',
    title: '矢場丼 名古屋站名鐵店',
    subTitle: '名鐵百貨 9 樓',
    description: '必吃味噌豬排。假日須排隊。',
    category: Category.FOOD,
    locationKeyword: 'Yabaton Meitetsu Nagoya',
    imageUrl: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&q=80&w=600',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '1-3',
    day: 1,
    time: '15:00',
    title: 'JR 名古屋高島屋 Gate Tower',
    subTitle: '11F UNIQLO',
    description: '與高島屋連通。可順便看艾許奶油 Échiré。',
    category: Category.ACTIVITY,
    locationKeyword: 'JR Nagoya Takashimaya Gate Tower Mall',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '1-4',
    day: 1,
    time: '19:45',
    title: '味藏天國 (Ajikura Tengoku)',
    subTitle: 'A5 飛驒牛',
    description: '預約 19:45。必點：A5 飛驒牛拼盤、骰子牛。',
    category: Category.FOOD,
    locationKeyword: 'Ajikura Tengoku',
    imageUrl: 'https://images.unsplash.com/photo-1514356630444-62da7c09a302?auto=format&fit=crop&q=80&w=600',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '1-5',
    day: 1,
    time: '21:00',
    title: 'WAT 飯店 & SPA 飛驒高山',
    subTitle: '高山住宿',
    description: '提供溫泉泡湯，回飯店放鬆。',
    category: Category.LOGISTICS,
    locationKeyword: 'WAT HOTEL & SPA HIDA TAKAYAMA',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  // Day 2
  {
    id: '2-1',
    day: 2,
    time: '09:00',
    title: '新穗高纜車 🔭',
    subTitle: '2156m 雲上絕景',
    description: '搭乘雙層纜車上山頂展望台，看北阿爾卑斯山雪牆。',
    category: Category.SCOUTING,
    locationKeyword: 'Shinhotaka Ropeway',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&q=80&w=600',
    isDeleted: false,
    expenses: [],
    notes: ['需搭兩段纜車', '山頂有咖啡廳與全景休息室']
  },
  {
    id: '2-2',
    day: 2,
    time: '15:00',
    title: '高山老街 (上三之町)',
    subTitle: '老街散策',
    description: '飛驒牛握壽司、五平餅、御手洗團子。',
    category: Category.ACTIVITY,
    locationKeyword: 'Sanmachi Suji',
    isDeleted: false,
    expenses: [],
    notes: ['飛驒牛握壽司必吃', '逛清酒釀造廠']
  },
  // Day 3
  {
    id: '3-1',
    day: 3,
    time: '08:00',
    title: '宮川朝市',
    subTitle: '高山活力晨間',
    description: '逛逛當地攤位，有新鮮水果和工藝品。',
    category: Category.ACTIVITY,
    locationKeyword: 'Miyagawa Morning Market',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '3-2',
    day: 3,
    time: '09:35',
    title: '濃飛巴士 (高山 -> 白川鄉)',
    subTitle: '合掌村之旅',
    description: '預計 10:25 抵達白川鄉。',
    category: Category.TRANSPORT,
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '3-3',
    day: 3,
    time: '11:00',
    title: '城山天守閣展望台 🔭',
    subTitle: '合掌村全景',
    description: '卡位拍攝童話般的合掌村。',
    category: Category.SCOUTING,
    locationKeyword: 'Shiroyama Tenshukaku Observatory',
    isDeleted: false,
    expenses: [],
    notes: ['接駁車每 20 分鐘一班']
  },
  {
    id: '3-4',
    day: 3,
    time: '12:30',
    title: '白川鄉合掌村漫遊',
    subTitle: '世界遺產巡禮',
    description: '參觀和田家、明善寺、相逢橋。',
    category: Category.ACTIVITY,
    locationKeyword: 'Shirakawa-go',
    imageUrl: 'https://images.unsplash.com/photo-1542641728-6ca359b085f4?auto=format&fit=crop&q=80&w=600',
    isDeleted: false,
    expenses: [],
    notes: ['小吃推薦：飛驒牛壽司、五平餅']
  },
  {
    id: '3-5',
    day: 3,
    time: '19:00',
    title: '海老どて食堂 (ESCA)',
    subTitle: '35cm 巨大炸蝦',
    description: '位於名古屋站 ESCA 地下街，霸氣炸蝦晚餐。',
    category: Category.FOOD,
    locationKeyword: 'Ebi Dote Shokudo',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  // Day 4
  {
    id: '4-1',
    day: 4,
    time: '07:30',
    title: 'BUCYO COFFEE KAKO',
    subTitle: '經典小倉紅豆吐司',
    description: '紅豆鮮奶油吐司配上深焙咖啡。',
    category: Category.FOOD,
    locationKeyword: 'BUCYO Coffee',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '4-2',
    day: 4,
    time: '09:00',
    title: '名古屋城 🏯',
    subTitle: '歷史巡禮',
    description: '參觀本丸御殿，欣賞金碧輝煌的障壁畫。',
    category: Category.ACTIVITY,
    locationKeyword: 'Nagoya Castle',
    imageUrl: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&q=80&w=600',
    isDeleted: false,
    expenses: [{ id: 'nc1', item: '門票', amount: 500 }],
    notes: ['天守閣目前整修中無法進入']
  },
  {
    id: '4-3',
    day: 4,
    time: '14:00',
    title: 'HARBS 榮本店 🍰',
    subTitle: '必吃水果千層',
    description: '朝聖 HARBS 發源地，品嚐招牌水果千層蛋糕。',
    category: Category.FOOD,
    locationKeyword: 'HARBS Sakae',
    isDeleted: false,
    expenses: [],
    notes: ['本店限定口味必試']
  },
  {
    id: '4-4',
    day: 4,
    time: '18:00',
    title: '綠洲 21 & 電視塔 🔭',
    subTitle: '水の宇宙船夜景 🌃',
    description: '拍攝中部電力 Mirai Tower 最美卡位點。',
    category: Category.SCOUTING,
    locationKeyword: 'Oasis 21',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  // Day 5
  {
    id: '5-1',
    day: 5,
    time: '08:00',
    title: '柳橋中央市場',
    subTitle: '海鮮食堂',
    description: '名古屋的廚房，享用最新鮮的海鮮丼。',
    category: Category.FOOD,
    locationKeyword: 'Yanagibashi Central Market',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '5-2',
    day: 5,
    time: '09:30',
    title: '熱田神宮 ⛩️',
    subTitle: '三大神器之一',
    description: '供奉草薙劍的神聖之地。',
    category: Category.ACTIVITY,
    locationKeyword: 'Atsuta Jingu',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '5-3',
    day: 5,
    time: '11:30',
    title: 'あつた蓬莱軒 鰻魚飯',
    subTitle: '鰻魚飯三吃',
    description: '經典原味、配料、茶泡飯三種享受。',
    category: Category.FOOD,
    locationKeyword: 'Atsuta Houraiken Jingu',
    imageUrl: 'https://images.unsplash.com/photo-1581264692574-e7ba76698650?auto=format&fit=crop&q=80&w=600',
    isDeleted: false,
    expenses: [],
    notes: ['10:45 建議先去門口登記']
  },
  {
    id: '5-4',
    day: 5,
    time: '14:00',
    title: '大須商店街 / 三輪神社',
    subTitle: '雜貨與可愛兔子',
    description: '逛街尋找可愛的兔子石像。',
    category: Category.ACTIVITY,
    locationKeyword: 'Osu Kannon',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '5-5',
    day: 5,
    time: '19:00',
    title: '千里馬藥局',
    subTitle: '最後採購',
    description: '藥妝戰利品最後衝刺，22:00 關門。',
    category: Category.ACTIVITY,
    locationKeyword: 'Senrima Drugstore',
    isDeleted: false,
    expenses: [],
    notes: ['2樓退稅僅限現金']
  },
  // Day 6
  {
    id: '6-1',
    day: 6,
    time: '06:48',
    title: '名鐵機場特急 μ-SKY',
    subTitle: '市區 -> 機場',
    description: '約 07:20 抵達中部機場 T1。',
    category: Category.TRANSPORT,
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '6-2',
    day: 6,
    time: '08:00',
    title: '機場蝦餅 えびせんべいの里',
    subTitle: '最後伴手禮',
    description: '機場必買超人氣蝦餅。',
    category: Category.ACTIVITY,
    locationKeyword: 'Ebisensbei no Sato',
    isDeleted: false,
    expenses: [],
    notes: []
  },
  {
    id: '6-3',
    day: 6,
    time: '09:50',
    title: '中華航空 CI 151',
    category: Category.HUB,
    flightInfo: {
      flightNumber: 'CI 151',
      origin: 'NGO - 中部國際',
      destination: 'TPE - 桃園',
      class: 'Economy',
      duration: '2h 25m',
      passengerNames: ['PaoPao', '孟哲']
    },
    isDeleted: false,
    expenses: [],
    notes: ['12:15 抵達桃園']
  }
];
